mybatis:
   configuration:
      map-underscore-to-camel-case: true

---

spring:
   profiles: dev
   devtools:
      restart:
         additional-paths:
            - src/main/java
            - application.yml
         exclude: static/**,public/**
   thymeleaf:
      cache: false
      session:
         store-type: none

logging:
   level:
      org.angboot: debug

management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint:
      health:
         show-details: always

---

spring:
   profiles: test
server:
   port: 10001

---

spring:
   profiles: prod
