spring:
  profiles:
    active: dev
#  resources:
#    static-locations:
#      - classpath:/META-INF/resources/
#      - classpath:/resources/
#      - classpath:/static/
#      - classpath:/public/
#      - classpath:/app/

---

spring:
  profiles: dev
  devtools:
    restart:
      additional-paths:
      - src/main/java
      - application.yml
      exclude: static/**,public/**,app/**
  thymeleaf:
    cache: false
    session:
      store-type: none

server:
  port: 9999

---

spring:
  profiles: test
server:
  port: 10001

---

spring:
  profiles: prod


