spring:
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths:
        - src/main/java
        - application.yml
      exclude: static/**,public/**,app/**
server:
  error:
    path: app/index.html

---

spring:
  profiles: dev
server:
  port: 80

---

spring:
  profiles: test
server:
  port: 10001

---

spring:
  profiles: prod


